apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ovpn-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ovpn.hfs.dev
    secretName: ovpn-tls
  rules:
  - host: ovpn.hfs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ovpn
            port:
              number: 80
